"""Tally every annotation text in the shipped animation archive (the census
extraction of lane HKXEDIT1, scratchpad/hkxedit1_20260910/census_hkx/), via
the independent oracle reader. Output: res/hkx_annotation_vocabulary.txt
(one line per name: count<TAB>name, most frequent first) -- the vocabulary the
workspace offers when adding an annotation. Emitted by tooling from the game's
own files, never hand-authored (CONSTITUTION 10, zero-authoring)."""
import sys, os, collections
sys.path.insert(0, r"E:\Projects\NifskopeWildWastelandEdition\tests\spells")
import hkxfile_oracle as O
ROOT = r"E:\Projects\NifskopeWildWastelandEdition"
db = O.ClassDb(os.path.join(ROOT, "res", "hkclasses_fo4.json"))
src = os.path.join(ROOT, "scratchpad", "hkxedit1_20260910", "census_hkx")
tally = collections.Counter()
files = 0; withann = 0; refused = 0
for relpath, blob in O.iter_files(src):
    files += 1
    try:
        pf = O.read(blob, db)
    except Exception:
        refused += 1; continue
    found = 0
    for obj in pf.objects:
        cname = obj["c"]
        if not cname.startswith("hka") or "Animation" not in cname:
            continue
        members = db.all_members(cname)
        v = None
        for m, val in zip(members, obj["v"]["m"]):
            if m["name"] == "annotationTracks":
                v = val
        if v is None or v["k"] != "arr":
            continue
        for track in v["e"]:
            for m, val in zip(db.all_members(track["c"]), track["m"]):
                if m["name"] == "annotations":
                    for a in val["e"]:
                        for mm, vv in zip(db.all_members(a["c"]), a["m"]):
                            if mm["name"] == "text":
                                s_ = vv["s"]
                                tally[(s_ or b"").decode("latin-1")] += 1
                                found += 1
    if found:
        withann += 1
print("files", files, "with annotations", withann, "refused", refused, "distinct", len(tally), "total", sum(tally.values()))
out = os.path.join(ROOT, "res", "hkx_annotation_vocabulary.txt")
with open(out, "wb") as f:
    f.write(b"# hkaAnnotationTrack::Annotation texts in Fallout4 - Animations.ba2, count<TAB>name\n")
    f.write(("# generated by scratchpad/hkxedit2_20260910/annot_vocab.py over %d files; %d distinct, %d total\n" % (files, len(tally), sum(tally.values()))).encode())
    skipped = 0
    for name, n in tally.most_common():
        # a shipped name carrying a control character (two carry a carriage
        # return) cannot be a vocabulary line: the file stays LF-only
        if any(ord(ch) < 32 for ch in name):
            skipped += 1
            continue
        f.write(("%d\t%s\n" % (n, name)).encode("utf-8"))
print("wrote", out, "skipped names with control characters:", skipped)
