#!/bin/bash
#
# Build the X-01 Tesla loading screen, effects and all.
#
# The whole point of this file is that the order is NOT obvious and getting it
# wrong produces something that loads fine and is wrong.
#
#   1. MERGE WITH THE EFFECTS STILL LIVE. The obvious pipeline freezes each
#      effect file first and then merges -- that is what tests/merge/
#      artobject_attach.sh does, because a frozen file is what a finished screen
#      wants. But freezing STRIPS the controller graph, and the arcs and sprites
#      are generated BY that graph: freeze first and there is nothing left to
#      snapshot. So the VFX files go in live.
#
#   2. SNAPSHOT ON THE ASSEMBLED RIG, not per file. A baked shape is written in
#      the space it was captured in. Capture a helmet effect in its own file and
#      the coordinates are helmet-local; the merge would then have to rebase
#      them, and it only knows how to do that for NamedAttach branches, which a
#      baked shape is not. On the assembled rig everything is already in actor
#      space, so no rebase is needed and none happens.
#
#   3. Only then convert. By that point the effects are ordinary geometry and the
#      converter treats them as such.
#
# Step 2 needs the GUI: a bake reads the RENDERED scene, because that is the only
# place a sprite quad or a lightning ribbon exists. It opens a window briefly.
#
# THE OTHER WAY: --live
#
# Since 2026-07-31f the convert can keep the ArtObject branches RUNNING instead,
# on a stub of the bone they hung from (loading-screen --keep-effects). That skips
# the snapshot entirely -- there is nothing to freeze -- and needs no GUI at all.
# What it gives up is precedent: no vanilla loading screen contains a particle
# system, while 18 of the 173 animate node transforms and CreatureBloatfly.nif
# carries a full controller manager and sequence. Both files are identical up to
# the merge, so the two can be compared in game directly.
#
# USAGE
#   bash tools/make_x01_loadscreen.sh [time] [outfile]
#   bash tools/make_x01_loadscreen.sh --live [outfile]
# Default time 2.5 s. Writes into the X01Tesla mod folder unless told otherwise.

set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
EXE="${EXE:-$ROOT/release/NifSkope.exe}"
SK="${SK:-/e/Tools/Fallout 4/DataUnpacked/Data/meshes/actors/powerarmor/CharacterAssets/skeleton.nif}"
X="${X:-/e/Projects/Fallout 4 Mods/mods/X01Tesla/meshes/actors/powerarmor/x01}"
CA="${CA:-/e/Tools/Fallout 4/DataUnpacked/Data/meshes/actors/powerarmor/CharacterAssets}"
LIVE=0
if [ "${1:-}" = "--live" ]; then LIVE=1; shift; fi
TIME="2.5"
[ "$LIVE" = "0" ] && TIME="${1:-2.5}"
DEFOUT="/e/Projects/Fallout 4 Mods/mods/X01Tesla/meshes/LoadScreenArt/X01TeslaLoadScreen.nif"
if [ "$LIVE" = "1" ]; then OUT="${1:-$DEFOUT}"; else OUT="${2:-$DEFOUT}"; fi
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

[ -x "$EXE" ] || { echo "no NifSkope.exe at $EXE"; exit 2; }
[ -f "$SK" ]  || { echo "no skeleton at $SK"; exit 2; }

# --- 1. assemble, effects live ----------------------------------------------
# Base armour, then the Tesla HARDWARE layer (the coils -- a layer, not a
# variant), then the VFX that hangs off it.
add=()
for p in Helmet Torso ArmLeft ArmRight LegLeft LegRight; do
	for f in "X01_$p.nif" "X01_${p}_Tesla.nif" "X01_${p}_Tesla_VFX.nif"; do
		[ -f "$X/$f" ] && add+=( --add "$X/$f" )
	done
done
[ -f "$CA/Frame.nif" ] && add+=( --add "$CA/Frame.nif" )

echo "1. merging ${#add[@]} donors onto the skeleton (effects live)"
"$EXE" -no-gui merge "$SK" "${add[@]}" -o "$TMP/rig.nif" > "$TMP/merge.log" 2>&1 \
	|| { echo "   merge FAILED"; cat "$TMP/merge.log"; exit 1; }
sed -n 's/^  branches attached by name to/   attached by name ->/p;s/^  \([0-9]* bone name\)/   \1/p' "$TMP/merge.log"
echo "   $("$EXE" -no-gui info "$TMP/rig.nif" 2>/dev/null | sed -n 's/^blocks *\([0-9]*\)/\1 blocks/p')"

if [ "$LIVE" = "1" ]; then

# --- 2/3. straight to the convert, effects still running --------------------
echo "2. converting with the effects left live (no snapshot, no GUI)"
"$EXE" -no-gui loading-screen "$TMP/rig.nif" --keep-effects -o "$TMP/screen.nif" \
	> "$TMP/conv.log" 2>&1 || { echo "   convert FAILED"; cat "$TMP/conv.log"; exit 1; }
sed -n 's/^  \([0-9]* effect branch\)/   \1/p' "$TMP/conv.log"
sed -n 's/^  note: \(BSXFlags[^,]*\)/   \1/p' "$TMP/conv.log"

else

# --- 2. snapshot the effects, in the GUI ------------------------------------
echo "2. snapshotting effects at t=$TIME (opens a window)"
LOG="$ROOT/release/ww_effectbake_test.log"
rm -f "$LOG"
WW_EFFECTBAKE_TEST="$TMP/baked.nif" WW_EFFECTBAKE_TIME="$TIME" WW_WINDOW_AT="1960,20" \
	"$EXE" --port 41893 "$TMP/rig.nif" > /dev/null 2>&1
if [ ! -s "$TMP/baked.nif" ]; then
	echo "   snapshot FAILED -- no file produced"
	[ -f "$LOG" ] && sed -n 's/^/   /p' "$LOG"
	exit 1
fi
sed -n 's/^\(captured\|wrote\|worst\)/   &/p' "$LOG"
grep -q '^PASS' "$LOG" || { echo "   snapshot checks FAILED:"; grep '^  FAIL' "$LOG" | sed 's/^/   /'; }

# --- 3. convert -------------------------------------------------------------
echo "3. converting to loading-screen art"
"$EXE" -no-gui loading-screen "$TMP/baked.nif" -o "$TMP/screen.nif" > "$TMP/conv.log" 2>&1 \
	|| { echo "   convert FAILED"; cat "$TMP/conv.log"; exit 1; }
sed -n 's/^\(baked\|dropped\|LoadingMenuZoomTarget\)/   &/p' "$TMP/conv.log" | head -6

fi

# --- 4. measure what came out ----------------------------------------------
echo "4. where everything landed"
blocks="$("$EXE" -no-gui info "$TMP/screen.nif" 2>/dev/null | sed -n 's/^blocks *\([0-9]*\)/\1/p')"
list="$("$EXE" -no-gui list "$TMP/screen.nif" 2>/dev/null)"
shapes=0; effects=0
for b in $(seq 0 $(( blocks - 1 )) ); do
	row="$(echo "$list" | grep "^\[$b\]")"
	case "$row" in *TriShape*) ;; *) continue ;; esac
	shapes=$((shapes+1))
	nm="$(echo "$row" | sed "s/.*'\(.*\)'/\1/")"
	v="$("$EXE" -no-gui get "$TMP/screen.nif" -b "$b" -f "Translation" 2>/dev/null)"
	case "$nm" in BoltGeo*|Lightning*|*Arc*|*Pulse*|*Spark*)
		effects=$((effects+1)); printf '   fx  %-34s %s\n' "$nm" "$v" ;;
	esac
done
left="$(echo "$list" | grep -cE "NiParticleSystem|NiPSys|BSPSys|BSProceduralLightningController")"
if [ "$LIVE" = "1" ]; then
	echo "   $shapes shapes total, $effects of them effect geometry (the rest is generated at runtime)"
	echo "   emitter blocks kept alive: $left"
	[ "$left" -gt 0 ] || echo "   WARNING: nothing left to run -- the branches were not kept"
else
	echo "   $shapes shapes total, $effects of them baked effects"
	echo "   emitter blocks remaining: $left"
fi

# --- 5. ship ----------------------------------------------------------------
mkdir -p "$(dirname "$OUT")"
cp -f "$TMP/screen.nif" "$OUT" || exit 1
echo "5. wrote $OUT ($(stat -c%s "$OUT") bytes)"
